#!/usr/bin/env perl
use strict;
use warnings;
use Time::HiRes qw(gettimeofday tv_interval);
use Getopt::Long;
use Carp;
use lib qw(lib);
use palign qw(readfa hash align attach detach report refs);

my $opts = {};
GetOptions($opts, qw(k=s index=s query report refs full)) or exit 1;
if($opts->{k}) {
    $palign::k = $opts->{k};
}

if(!$opts->{index}) {
  $opts->{index} = 'index.stbl';
}

my $t0     = [gettimeofday];
my @inputs = @ARGV;
my $action = [grep { $opts->{$_} } qw(report query refs index)]->[0]; # order important

# open database
attach($opts->{index} || 'index.stbl', {index => 'rw'}->{$action} || 'ro');

{
    report => \&report,
    query  => sub {
	readfa(\&align, @inputs);
	print "Aligned in @{[tv_interval $t0]} secs\n";
    },
    refs   => sub {
	refs($opts->{full}, @inputs);
    },
    index  => sub {
	readfa(\&hash, @inputs);
	print "Built hashtable in @{[tv_interval $t0]} secs\n";
    }
}->{$action}->();

# close database
detach();
